#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "Index Products on Vector Database"
topics:
  - name: "vectors-topic"
    creation-mode: create-if-not-exists
assets:
  - name: "es-index"
    asset-type: "elasticsearch-index"
    creation-mode: create-if-not-exists
    config:
      datasource: "elasticsearch-datasource"
      index: "e5_mistral_7b_instruct"
      settings: |
        {
             "index": {
                   "knn": true,
                   "knn.algo_param.ef_search": 100
             }
         }
      mappings: |
        {
             "properties": {
                   "vecPlanId": {
                         "type": "keyword"
                   },
                   "vector": {
                         "type": "knn_vector",
                         "dimension": 1536
                   }
             }
         }
errors:
    on-failure: skip
pipeline:
  - name: "convert-to-json"
    type: "document-to-json"
    input: "vectors-topic"
    configuration:
      text-field: "document"
  - name: "compute-embeddings"
    type: "compute-ai-embeddings"
    configuration:
      model: "${secrets.open-ai.embeddings-model}" # This needs to match the name of the model deployment, not the base model
      embeddings-field: "value.embeddings"
      text: "{{ value.document }}"
      batch-size: 10
      flush-interval: 500
  - name: "Write to vector db"
    type: "vector-db-sink"
    configuration:
      datasource: "elasticsearch-datasource"
      index: "e5_mistral_7b_instruct"
      fields:
        - name: "embeddings"
          expression: "value.embeddings"
        - name: "text"
          expression: "value.document"